version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
jobs:
  runner-test:
    machine: true
    # resource_class: yuji-hatakeyama/hello-test
    resource_class: yuji-hatakeyama/centos7-test
    parallelism: 3
    steps:
      - checkout
      - run: echo "Hi I'm on Runners!"
      - run: whoami
      - run: date
      - run: hostname
      - run:
          name: Test application
          command: |
              TEST=$(circleci tests glob "tests/**.sh" | circleci tests split --split-by=timings)
              echo $TEST;
              for script in $TEST; do bash "$script"; done
